== 起動時のエラー [[failed-to-load]]
//Startup Errors [[failed-to-load]]

////
Sometimes `shadow-cljs` can fail to start properly. The errors are often very confusing and hard to identify. Most commonly this is caused by a few dependency conflicts on some of the important dependencies. When using just `shadow-cljs.edn` to manage your `:dependencies` it will provide a few extra checks to protect against these kinds of errors but when using `deps.edn` or `project.clj` these protections cannot be done so these errors happen more often when using those tools.
////
時々 `shadow-cljs` が正しく起動しないことがあります。このエラーはしばしば非常に分かりづらく、特定するのが困難です。最も一般的な原因は、いくつかの重要な依存関係が衝突していることです。単に `:dependencies` の管理に `shadow-cljs.edn` を使用している場合には、これらの種類のエラーから守るためにいくつかの特別なチェックを行いますが、`deps.edn` や `project.clj` を使用している場合には、これらの保護を行うことができないため、これらのツールを使用している場合には、これらのエラーがより頻繁に発生します。

////
Generally the important dependencies to watch out for are
////
一般的に、注意すべき重要な依存関係は以下の通りです。

////
- org.clojure/clojure
- org.clojure/clojurescript
- org.clojure/core.async
- com.google.javascript/closure-compiler-unshaded
////

////
Each `shadow-cljs` version is only tested with one particular combination of versions and it is recommended to stick with that version set for best compatibility. It might work when using different versions but if you encounter any kind of weird issues consider fixing your dependency versions first.
////
各 `shadow-cljs` バージョンは、ある特定のバージョンの組み合わせでしかテストされておらず、最良の互換性を得るためには、そのバージョンセットに固執することが推奨されます。異なるバージョンを使用している場合でも動作するかもしれませんが、何らかのおかしな問題が発生した場合は、まず依存するバージョンの修正を検討してください。

////
You can find the required dependencies for each version on clojars:
////
各バージョンに必要な依存関係は、clojarsで確認できます。

- https://clojars.org/thheller/shadow-cljs

////
The way to diagnose these issues vary by tool, so please refer to the appropriate section for further info.
////
これらの問題を診断する方法はツールによって異なりますので、詳細は該当するセクションを参照してください。

////
Generally if you want to be sure you can just declare the matching dependency versions directly together with your chosen `shadow-cljs` version but that means you must also update those versions whenever you upgrade `shadow-cljs`. Correctly identifying where unwanted dependencies may be more work but will make future upgrades easier.
////
一般的に、確実にしたいのであれば、選択した `shadow-cljs` のバージョンと一緒に、一致する依存関係のバージョンを直接宣言すればよいのですが、それは `shadow-cljs` をアップグレードするたびに、それらのバージョンも更新しなければならないことを意味します。不要な依存関係を正しく特定することは、より多くの作業を必要とするかもしれませんが、将来のアップグレードを容易にするでしょう。

////
`shadow-cljs` will likely always be on the very latest version for all the listed dependencies above so if you need to stick with an older dependency you might need to stick with an older shadow-cljs version as well.
////
shadow-cljs` は、上に挙げたすべての依存関係について常に最新のバージョンである可能性が高いため、古い依存関係を維持する必要がある場合は、shadow-cljs のバージョンも古いものにする必要があるかもしれません。

////
`shadow-cljs` is very often several versions ahead on the `com.google.javascript/closure-compiler-unshaded` version it uses, so if you are depending on the version `org.clojure/clojurescript` normally supplies that might cause issues. Make sure the `thheller/shadow-cljs` version is picked over the version preferred by `org.clojure/clojurescript`.
////
そのため、`org.clojure/clojurescript` が通常提供しているバージョンに依存していると、問題が発生する可能性があります。そのため、`org.clojure/clojurescript` が通常供給するバージョンに依存している場合、問題が発生する可能性があります。

////
If you want to make your live easier just use `shadow-cljs.edn` to manage your dependencies if you can. It is much less likely to have these problems or will at least warn you directly.
////
もし、あなたの生活をより楽にしたいのであれば、できれば `shadow-cljs.edn` を使って依存関係を管理してください。このような問題が発生する可能性は非常に低いですし、少なくともあなたに直接警告してくれます。

////
If you have ensured that you are getting all the correct versions but things still go wrong please open a https://github.com/thheller/shadow-cljs/issues[Github Issue] with a full problem description including your full dependency list.
////
正しいバージョンを入手したにもかかわらず、問題が解決しない場合は、https://github.com/thheller/shadow-cljs/issues[Github Issue]を開き、依存関係のリストを含む問題の詳細をご報告ください。

=== deps.edn / tools.deps

////
When using `deps.edn` to manage your dependencies via the <<tools-deps, :deps>> key in `shadow-cljs.edn` it is recommended to use the `clj` tool directly for further diagnosis. First you need to check which aliases you are applying via `shadow-cljs.edn`. So if you are setting `:deps {:aliases [:dev :cljs]}` you'll need to specify these aliases when running further commands.
////
shadow-cljs.edn` の <<tools-deps, :deps>> キーで依存関係を管理するために `deps.edn` を使用している場合、さらなる診断のために `clj` ツールを直接使用することが推奨されます。まず最初に、あなたが `shadow-cljs.edn` を通してどのエイリアスを適用しているかを確認する必要があります。つまり、もしあなたが `:deps {:aliases [:dev :cljs]}` を設定しているのであれば、さらにコマンドを実行する際に、これらのエイリアスを指定する必要があります。

////
First of all you should ensure that all dependencies directly declared in `deps.edn` have the expected version. Sometimes transitive dependencies can cause the inclusion of problematic versions. You can list all dependencies via:
////
まず最初に、`deps.edn` で直接宣言されているすべての依存関係が、期待されるバージョンであることを確認する必要があります。推移的な依存関係によって、問題のあるバージョンが含まれていることがあります。すべての依存関係をリストアップするには、以下の方法があります。

////
.Listing all active dependencies
////
.アクティブな依存関係をすべてリストアップ

```bash
$ clj -A:dev:cljs -Stree
```

////
This will list all the dependencies. Tracking this down is a bit manual but you'll need to verify that you get the correct versions for the dependencies mentioned above.
////
これにより、すべての依存関係がリストアップされます。これを追いかけるのはちょっと大変ですが、上述の依存関係のために正しいバージョンを取得しているかどうかを確認する必要があります。

////
Please refer to the official https://clojure.org/reference/deps_and_cli[tools.deps] documentation for further information.
////
詳細は、https://clojure.org/reference/deps_and_cli[tools.deps]の公式ドキュメントをご参照ください。

=== project.clj / Leiningen

////
When using `project.clj` to manage you dependencies you'll need to specify your configured `:lein` profiles from `shadow-cljs.edn` when using `lein` directly to diagnose the problem. For example `:lein {:profiles "+cljs"}` would require `lein with-profiles +cljs` for every command.
////
project.clj` を使って依存関係を管理している場合、`lein` を直接使って問題を診断するときには、`shadow-cljs.edn` から設定した `:lein` プロファイルを指定する必要があります。例えば、 `:lein {:profiles "+cljs"}` とすると、すべてのコマンドに対して `lein with-profiles +cljs` が必要になります。

////
.Example listing of deps
////
.例 deps のリスト

```
# no profile
$ lein deps :tree

# with profile
$ lein with-profiles +cljs deps :tree
```

////
This will usually list all the current conflicts at the top and provide suggestions with the dependency tree at the bottom. The suggestions aren't always fully accurate so don't get mislead and don't add exclusions to the `thheller/shadow-cljs` artifact.
////
これは通常、一番上に現在のコンフリクトをすべてリストアップし、一番下に依存関係のツリーで提案を提供します。提案は必ずしも完全には正確ではありませんので、誤解を招かないように、また `thheller/shadow-cljs` アーティファクトに除外項目を追加しないようにしてください。

////
Please refer to the https://leiningen.org/[Leiningen] documentation for more information.
////
詳しくは、https://leiningen.org/[Leiningen]のドキュメントをご参照ください。