== NPM [[npm]]

////
https://www.npmjs.com/[npm] has become the de-facto standard package manager for JavaScript. Almost all JS libraries can be found there and shadow-cljs provides seamless integration for accessing those packages.
////
https://www.npmjs.com/[npm] は、JavaScriptのデファクトスタンダードのパッケージマネージャとなっています。ほとんどすべての JS ライブラリはそこで見つけることができ、shadow-cljs はそれらのパッケージにアクセスするためのシームレスな統合を提供します。

=== npmパッケージの使用
//Using npm packages

////
Most npm packages will also include some instructions on how to use the actual code. The “old” CommonJS style just has `require` calls which translate directly:
////
ほとんどのnpmパッケージには、実際のコードの使用方法に関する説明も含まれています。古いCommonJSのスタイルでは、直接翻訳する `require` コールがあるだけです。

```js
var react = require("react");
```

```
(ns my.app
  (:require ["react" :as react]))
```

////
Whatever "string" parameter is used when calling require we transfer to the `:require` as-is. The `:as` alias is up to you. Once we have that we can use the code like any other CLJS namespace!
////
requireを呼び出すときに使われたどんな "string "パラメータも、そのまま `:require` に転送されます。 `as` のエイリアスはあなた次第です。これができたら、他のCLJSの名前空間と同じようにコードを使うことができます。

```
(react/createElement "div" nil "hello world")
```

////
In `shadow-cljs`: *always use the `ns` form and whatever `:as` alias you provided.* You may also use `:refer` and `:rename`. This is different than what `:foreign-libs`/CLJSJS does where you include the thing in the namespace but then used a global `js/Thing` in your code.
////
`shadow-cljs` では。*常に `ns` 形式と、あなたが提供した `:as` のエイリアスを使用してください。* また、 `:refer` や `:rename` を使用することもできます。これは、 `:foreign-libs`/CLJSJSが行う、名前空間にものをインクルードしても、コードの中ではグローバルな `js/Thing` を使用するというものとは異なります。

////
Some packages just export a single function which you can call directly by
using `(:require ["thing" :as thing])` and then `(thing)`.
////
パッケージの中には、1つの関数をエクスポートするものもあります。
(:require ["thing" :as thing])` and then `(that)` を使って直接呼び出すことができます。

////
More recently some packages started using ES6 `import` statements in their examples. Those also translate pretty much 1:1 with one slight difference related to default exports.
////
最近では、いくつかのパッケージがES6の `import` 文を例に挙げています。これらもほぼ1:1で翻訳されていますが、デフォルトのエクスポートに関するわずかな違いがあります。

////
The following table can be used for translation:
////
以下の表は、翻訳に使用することができます。

////
IMPORTANT: This table only applies if the code you are consuming is packaged as actual ES6+ code. If the code is packaged as CommonJS instead the `:default` may not apply. See the section below for more info.
////
重要：この表は、消費されるコードが実際のES6+コードとしてパッケージされている場合にのみ適用されます。コードがCommonJSとしてパッケージされている場合は、 `:default` は適用されないかもしれません。詳細は以下のセクションを参照してください。

////
.ES6 Import to CLJS Require
////

.ES6をCLJSにインポートすることが必要

|===
|ES6 Import|CLJS Require

|`import defaultExport from "module-name";`
|`(:require ["module-name" :default defaultExport])`

|`import * as name from "module-name";`
|`(:require ["module-name" :as name])`

|`import { export } from "module-name";`
|`(:require ["module-name" :refer (export)])`

|`import { export as alias } from "module-name";`
|`(:require ["module-name" :rename {export alias}])`

|`import { export1 , export2 } from "module-name";`
|`(:require ["module-name" :refer (export1 export2)])`

|`import { export1 , export2 as alias2 , [...] } from "module-name";`
|`(:require ["module-name" :refer (export1) :rename {export2 alias2}])`

|`import defaultExport, { export [ , [...] ] } from "module-name";`
|`(:require ["module-name" :refer (export) :default defaultExport])`

|`import defaultExport, * as name from "module-name";`
|`(:require ["module-name" :as name :default defaultExport])`

|`import "module-name";`
|`(:require ["module-name"])`
|===

////
Notice that previously we were stuck using bundled code which included a lot of code we didn’t actually need. Now we're in a better situation:
Some libraries are also packaged in ways that allow you to include only the parts you need, leading to much less code in your final build.
////
以前は、実際には必要のない多くのコードを含むバンドルコードを使用していたことに注意してください。しかし、今回はより良い状況になりました。
ライブラリの中には、必要な部分だけをパッケージ化したものもあり、最終的なビルドに含まれるコードの量を大幅に減らすことができます。

////
`react-virtualized` is a great example:
////

////
```js
// You can import any component you want as a named export from 'react-virtualized', eg
import { Column, Table } from 'react-virtualized'

// But if you only use a few react-virtualized components,
// And you're concerned about increasing your application's bundle size,
// You can directly import only the components you need, like so:
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```
////

```js
// react-virtualizedから名前付きでエクスポートすることで、任意のコンポーネントをインポートすることができます。
import { Column, Table } from 'react-virtualized'

// しかし、いくつかのreact-virtualizedコンポーネントしか使用していない場合。
// また、アプリケーションのバンドルサイズが大きくなることを懸念している場合。
// 必要なコンポーネントだけを直接インポートすることができます。
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```

////
With our improved support we we can easily translate this to:
////

```
(ns my-ns
  ;; all
  (:require ["react-virtualized" :refer (Column Table)])
  ;; OR one by one
  (:require ["react-virtualized/dist/commonjs/AutoSizer" :default virtual-auto-sizer]
            ["react-virtualized/dist/commonjs/List" :default virtual-list]))
```

==== 概要 :default Exports
//About :default Exports

////
The `:default` option is currently only available in `shadow-cljs`, you can
https://dev.clojure.org/jira/browse/CLJS-2376[vote here] to hopefully make it standard. You can always use `:as alias` and then call `alias/default` if you prefer to stay compatible with standard CLJS in the meantime.
////
現在、 `:default` オプションは `shadow-cljs` でのみ利用可能です。
https://dev.clojure.org/jira/browse/CLJS-2376[vote here]で標準化されることを期待します。標準的なCLJSとの互換性を保ちたい場合は、いつでも `:as alias` を使用して、 `alias/default` を呼び出すことができます。

////
Default exports are a new addition in ECMAScript Modules and do not exist in CommonJS code. Sometimes you will see examples of `import Foo from "something"` when the code is actually CommonJS code. In theses cases `(:require ["something" :default Foo])` will not work and `(:require ["something" :as Foo])` must be used instead.
////
デフォルトのエクスポートは ECMAScript モジュールで新たに追加されたもので、CommonJS のコードには存在しません。時々、 `import Foo from "something"` という例を見かけることがありますが、実際にはCommonJSのコードです。このような場合、 `(:require ["something" :default Foo])` は動作せず、 `(:require ["something" :as Foo])` を代わりに使用する必要があります。

////
If a `:require` does not seem to work properly it is recommended to try looking at it in the REPL.
////
もし、 `:require` が正しく機能していないようであれば、REPL で見てみることをお勧めします。

```
$ shadow-cljs browser-repl (or node-repl)
...
[1:1]~cljs.user=> (require '["react-tooltip" :as x])
nil
[1:1]~cljs.user=> x
#object[e]
[1:1]~cljs.user=> (goog/typeOf x)
"function"
[1:1]~cljs.user=> (js/console.dir x)
nil
```

////
Since printing arbitrary JS objects is not always useful (as seen above) you can use `(js/console.dir x)` instead to get a more useful representation in the browser console. `goog/typeOf` may also be useful at times. Since the above example shows `"function"` using `:default` would not work since `:default` basically is just syntax sugar for `x/default`.
////
任意のJSオブジェクトを表示することは必ずしも便利ではないので（上の例のように）、代わりに `(js/console.dir x)` を使用すると、ブラウザのコンソールでより便利な表現を得ることができます。また、 `goog/typeOf` が役に立つ場合もあります。上の例では `"function"` を示しているので、 `:default` を使ってもうまくいきません。`:default` は基本的に `x/default` のシンタックスシュガーに過ぎないからです。

=== パッケージプロバイダ [[js-provider]]
//Package Provider [[js-provider]]

////
`shadow-cljs` supports several different ways to include `npm` packages into your build. They are configurable via the `:js-options :js-provider` setting. Each `:target` usually sets the one appropriate for your build most often you won't need to touch this setting.
////
`shadow-cljs` は、 `npm` パッケージをビルドに含めるためのいくつかの異なる方法をサポートしています。これらの方法は `:js-options :js-provider` 設定で設定できます。各 `:target` は通常、ビルドに適したものを設定しますが、ほとんどの場合、この設定を変更する必要はありません。

////
Currently there are 3 supported JS Providers:
////
現在、サポートされているJSプロバイダーは3つです。

////
[Horizontal]
`:require`:: Maps directly to the JS `require("thing")` function call. It is the default for all `node.js` targets since it can resolve `require` natively at runtime. The included JS is not processed in any way.
`:shadow`:: Resolves the JS via `node_modules` and includes a minified version of each referenced file in the build. It is the default for the `:browser` target. `node_modules` sources do not go through `:advanced` compilation.
`:closure`:: Resolves similarly to `:shadow` but attempts to process all included files via the Closure Compiler CommonJS/ES6 rewrite facilities. They will also be processed via `:advanced` compilation.
`:external`:: Only collects JS requires and emits an index file (configured via `:external-index "foo/bar.js"`) that is meant to be processed by any other JS build tool and will actually provide the JS dependencies. The emitted index file contains a bit of glue code so that the CLJS output can access the JS dependencies. The output of the external index file should be loaded before the CLJS output.
////

[Horizontal]
`:require`:: JSの `require("thing")` 関数呼び出しに直接マッピングします。実行時にネイティブで `require` を解決することができるため、すべての `node.js` ターゲットのデフォルトとなります。インクルードされたJSは何も処理されません。
`:shadow`:: JSを `node_modules` 経由で解決し、参照されている各ファイルの最小化されたバージョンをビルドに含めます。これは、 `:browser` ターゲットのデフォルトです。`node_modules` のソースは `:advanced` のコンパイルを通過しません。
`:closure`:: shadow` と同様に解決されますが、Closure Compiler CommonJS/ES6 rewrite facilities を通じて、含まれる全てのファイルを処理しようとします。これらのファイルは `:advanced` のコンパイルでも処理されます。
`:external`:: これは、他のJSビルドツールでも処理できるようになっており、実際にJSの依存関係を提供します。発行されたインデックス・ファイルには、CLJS の出力が JS の依存関係にアクセスできるようにするための、ちょっとしたグルー・コードが含まれています。外部インデックスファイルの出力は、CLJS 出力の前に読み込まれなければなりません。

.`:shadow` vs `:closure`

////
****
Ideally we want to use `:closure` as our primary JS Provider since that will run the entire application through `:advanced` giving us the most optimized output. In practice however lots of code available via `npm` is not compatible with the aggressive optimizations that `:advanced` compilation does. They either fail to compile at all or expose subtle bugs at runtime that are very hard to identify.

`:shadow` is sort of a stopgap solution that only processes code via `:simple` and achieves much more reliable support while still getting reasonably optimized code. The output is comparable (or often better) to what other tools like `webpack` generate.

Until support in Closure gets more reliable `:shadow` is the recommend JS Provider for `:browser` builds.
****
////

****
理想的には、主要な JS プロバイダとして `:closure` を使用したいところです。しかし実際には、 `npm` 経由で入手できる多くのコードは、 `:advanced` のコンパイルによる積極的な最適化とは互換性がありません。これらのコードは、まったくコンパイルできないか、実行時に特定が非常に困難な微妙なバグを露呈します。

shadow` は、 `:simple` を介してコードを処理するだけの、その場しのぎのソリューションのようなもので、適度に最適化されたコードを取得しつつ、より信頼性の高いサポートを実現しています。その出力は、 `webpack` のような他のツールが生成するものと同等(あるいはそれ以上)であることが多いです。

Closure のサポートがより確実なものになるまでは、 `:shadow` が `:browser` ビルドの推奨 JS プロバイダとなります。
****

////
.Example config for using `:closure` in a `:browser` build.
////
.例 : :browser のビルドで :closure を使用するための設定

```clojure
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options {:js-provider :closure}
   }}}
```

=== CommonJS vs ESM [[js-entry-keys]]
//CommonJS vs ESM [[js-entry-keys]]

////
Nowadays many `npm` packages ship multiple build variants. `shadow-cljs` will by default pick the variant linked under the `main` or `browser` key in `package.json`. This most commonly refers to CommonJS code. Some modern packages also provide a `module` entry which usually refers to ECMAScript code (meaning "modern" JS). Interop between CommonJS and ESM can be tricky so `shadow-cljs` defaults to using CommonJS but it can be beneficial to use ESM.
////
最近では、多くの `npm` パッケージが複数のビルドバリアントを出荷しています。shadow-cljs` はデフォルトで、 `package.json` の `main` または `browser` キーの下にリンクされているバリアントを選択します。これはほとんどの場合、CommonJS のコードを指しています。最近のパッケージの中には、 `module` エントリを提供しているものもありますが、これは通常 ECMAScript のコード (つまりモダンなJS) を指しています。CommonJS と ESM の間の相互運用は難しいので、 `shadow-cljs` のデフォルトは CommonJS を使用するようになっていますが、ESM を使用することが有益な場合もあります。

////
It is largely dependent on the packages you use whether this will work or not. You can configure `shadow-cljs`  to prefer the `module` entry via the `:entry-keys` JS option. It takes a vector of string keys found in `package.json` which will be tried in order. The default is `"["browser" "main" "module"]`.
////
これが機能するかどうかは、使用しているパッケージに大きく依存します。JS オプションの `:entry-keys` を使って、 `module` エントリを優先するように `shadow-cljs` を設定することができます。これは `package.json` に含まれる文字列キーのベクトルを受け取り、順番に試行されます。デフォルトでは `"["browser" "main" "module"]` となっています。

////
.Example config for using `:closure` in a `:browser` build.
////
.例 `:ブラウザ ` のビルドで `:クロージャ ` を使用するための設定です。

```clojure
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options {:entry-keys ["module" "browser" "main"]} ;; try "module" first
   }}}
```

////
Make sure to test thoroughly and compare the <<build-report, build report>> output to check size differences when switching this. Results may vary greatly in positive or negative ways.
////
これを切り替える際には、必ず十分なテストを行い、<<build-report, build report>>の出力を比較してサイズの違いを確認してください。結果は良い意味でも悪い意味でも大きく変わる可能性があります。

=== パッケージを解決する [[js-resolve]]
//Resolving Packages [[js-resolve]]

////
By default `shadow-cljs` will resolve all `(:require ["thing" :as x])` requires following the `npm` convention. This means it will look at `<project>/node_modules/thing/package.json` and follow the code from there. To customize how this works `shadow-cljs` exposes a `:resolve` config option that lets you override how things are resolved.
////
デフォルトでは `shadow-cljs` はすべての `(:require ["thing" :as x])` の要求を `npm` の規則に従って解決します。つまり、 `<project>/node_modules/thing/package.json` を見て、そこからコードを追っていきます。この動作をカスタマイズするために、 `shadow-cljs` は `:resolve` 設定オプションを公開しており、これによって物事がどのように解決されるかをオーバーライドすることができます。

==== CDNの利用 [[js-resolve-global]]

//Using a CDN [[js-resolve-global]]

////
Say you already have React included in your page via a CDN. You could just start using `js/React` again but we stopped doing that for a good reason. Instead you can continue to use `(:require ["react" :as react])` but configure how "react" resolves!
////
CDN経由ですでにReactがページに含まれているとします。`JS/React` を再び使い始めることもできますが、私たちは正当な理由でそれをやめました。その代わりに、 `(:require ["react" :as react])` を使い続けることができますが、"react "がどのように解決されるかを設定することができます。

////
Here is a sample `shadow-cljs.edn` config for such a build:
////

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :global
                       :global "React"}}}}

  :server
  {:target :node-script
   ...}}}
```

////
The `:app` build will now use the global `React` instance while the `:server` build continues using the "react" npm package! No need to fiddle with the code to make this work.
////
`app` のビルドでは、グローバルな `React` インスタンスが使用され、 `:server` のビルドでは、引き続き "react "npmパッケージが使用されます。これを動作させるためにコードをいじる必要はありません。

==== require をリダイレクトする [[js-resolve-npm]]
//Redirecting “require” [[js-resolve-npm]]

////
Sometimes you wan't more control over which `npm` package is actually used depending on your build. You can "redirect" certain requires from your build config without changing the code. This is often useful if you either don't have access to the sources using such packages or you just want to change it for one build.
////
ビルドに応じて、どの `npm` パッケージが実際に使用されるかをもっとコントロールしたい場合があります。コードを変更することなく、ビルド設定から特定のrequireをリダイレクトすることができます。これは、そのようなパッケージを使用しているソースにアクセスできない場合や、あるビルドのためだけに変更したい場合に便利です。


```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :npm
                       :require "preact-compat"}}}
```

////
You can also use a file to override the dependency, the path is relative to the project root.
////
また、ファイルを使って依存関係を上書きすることもできます。パスはプロジェクトルートからの相対パスです。

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :file
                       :file   "src/main/override-react.js"}}}
```

==== 制限事項 [[js-resolve-limitations]]
//Limitations [[js-resolve-limitations]]

////
The `:shadow-js` and `:closure` have full control over `:resolve` and everything mentioned above works without any downsides. The `:js-provider :require` however is more limited. Only the initial require can be influenced since the standard `require` is in control after that. This means it is not possible to influence what a package might `require` internally. It is therefore not recommended to be used with targets that use `require` directly (eg. `:node-script`).
////
shadow-js` と `:closure` は `:resolve` を完全に制御することができ、上記のすべてが欠点なく動作します。しかし、 `:js-provider :require` はより限定的です。最初のrequireにのみ影響を与えることができ、それ以降は標準の `require` が制御します。つまり、パッケージが内部で `require` するものに影響を与えることはできません。したがって、 `require` を直接使用するターゲット（例：`:node-script`）と一緒に使用することはお勧めできません。

////
.Redirecting "react" to "preact"
////
react を preact にリダイレクトする

```
{...
 :builds
 {:app
  {:target :node-script
   ...
   :js-options
   {:resolve {"react" {:target :npm
                       :require "preact-compat"}}}
```

////
.Example use of react-table
////
.例 react-table の利用

```
(ns my.app
  (:require
    ["react-table" :as rt]))
```

////
The above works fine in the Browser since every `"react"` require will be replaced, including the `"react"` require `"react-table"` has internally. For `:js-provider :require` however a `require("react-table")` will be emitted and `node` will be in control how that is resolved. Meaning that it will resolve it to the standard `"react"` and not the `"preact"` we had configured.
////
すべての `"react"` require が置換され、内部的に `"react-table"` が持っている `"react"` require を含むので、上記はブラウザでは問題なく動作します。しかし、 `:js-provider :require` では、 `require("react-table")` が発行され、 `node` はそれがどのように解決されるかをコントロールします。つまり、私たちが設定した `"preact"` ではなく、標準の `"react"` に解決されるということです。

=== 代替モジュールのディレクトリ [[alt-node-modules]]
//Alternate Modules Directories [[alt-node-modules]]

////
By default `shadow-cljs` will only look at the `<project-dir>/node_modules` directory when resolving JS packages. This can be configured via the `:js-package-dirs` option in `:js-options`. This can be applied globally or per build.
////
デフォルトでは `shadow-cljs` は JS パッケージを解決する際に `<project-dir>/node_modules` ディレクトリのみを見ます。これは、 `:js-options` の `:js-package-dirs` オプションで設定できます。これは、グローバルまたはビルドごとに適用することができます。

////
Relative paths will be resolved relative to the project root directory. Paths will be tried from left to right and the first matching package will be used.
////
相対パスは、プロジェクトのルートディレクトリを基準に解決されます。パスは左から右に向かって試行され、最初にマッチしたパッケージが使用されます。

////
.Global config in `shadow-cljs.edn`
////
shadow-cljs.edn のグローバル設定

```
{...
 :js-options {:js-package-dirs ["node_modules" "../node_modules"]}
 ...}
```

////
.Config applied to single build
////
.単一のビルドに適用される設定

```
{...
 :builds
 {:app
  {...
   :js-options {:js-package-dirs ["node_modules" "../node_modules"]}}}}
```


== .jsファイルへの対応 [[classpath-js]]
//Dealing with .js Files [[classpath-js]]

////
****
*DANGER: This feature is an experiment!* It is currently only supported in `shadow-cljs` and other CLJS tools will yell at you if you attempt to use it. Use at your own risk. The feature was initially rejected from CLJS core but I think it is useful and should not have been https://dev.clojure.org/jira/browse/CLJS-2061?focusedCommentId=46191&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46191[dismissed] without further discussion.

CLJS has an alternate https://clojurescript.org/guides/javascript-modules[implementation] which in turn is not supported by `shadow-cljs`. I found this implementation to be lacking in certain aspects so I opted for the different solution. Happy to discuss the pros/cons of both approaches though.
****
////

****
*DANGER: この機能は実験的なものです！* 現在は `shadow-cljs` でのみサポートされており、これを使おうとすると他の CLJS ツールに怒られます。自分の責任で使用してください。この機能は当初、CLJSのコアでは拒否されていましたが、私は便利だと思いますし、さらなる議論なしにhttps://dev.clojure.org/jira/browse/CLJS-2061?focusedCommentId=46191&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46191[dismissed]されるべきではなかったと思います。

CLJSには、https://clojurescript.org/guides/javascript-modules[implementation]という別の実装がありますが、これは `shadow-cljs` ではサポートされていません。私はこの実装がある種の面で不足していると感じたので、別の解決策を選びました。しかし、両方のアプローチの長所・短所を議論するのは楽しいことです。
****

////
We covered how <<npm, npm>> packages are used but you may be working on a codebase that already has lots of plain JavaScript and you don't want to rewrite everything in ClojureScript just yet. `shadow-cljs` provides 100% full interop between JavaScript and ClojureScript. Which means your JS can use your CLJS and CLJS can use your JS.
////
私たちは <<npm, npm>> パッケージがどのように使用されるかをカバーしましたが、あなたはすでに多くのプレーンな JavaScript を持つコードベースに取り組んでいるかもしれず、まだすべてを ClojureScript で書き直したくはないでしょう。shadow-cljs` は、JavaScriptとClojureScriptの間の100%完全な相互運用性を提供します。つまり、あなたのJSはあなたのCLJSを使うことができ、CLJSはあなたのJSを使うことができるということです。

////
There are only a few conventions you need to follow in order for this to work reliably but chances are that you are already doing that anyways.
////
この機能を確実に動作させるためには、いくつかの規則に従わなければなりませんが、すでに実行していることもあるでしょう。



=== JSをrequrieする
//Requiring JS

////
We already covered how `npm` packages are accessed by their name but on the classpath we access `.js` files by either a full path or relative to the current namespace.
////
先ほど、 `npm` パッケージに名前でアクセスする方法を説明しましたが、クラスパス上では、 `.js` ファイルにフルパスまたは現在の名前空間からの相対パスでアクセスします。

////
.Loading JS from the classpath
////
クラスパスから JS を読み込む

```clojure
(ns demo.app
  (:require
    ["/some-library/components/foo" :as foo]
    ["./bar" :as bar :refer (myComponent)]))
```

////
TIP: For string requires the extension `.js` will be added automatically but you can specify the extension if you prefer. Note that currently only `.js` is supported though.
////
ヒント：文字列が必要な場合、拡張子 `.js` が自動的に追加されますが、必要に応じて拡張子を指定することができます。ただし、現在は `.js` のみサポートしています。

////
Absolute requires like `/some-library/components/foo` mean that the compiler will look for a `some-library/components/foo.js` on the classpath; unlike `node` which would attempt to load the file from the local filesystem. The same classpath rules apply so the file may either be in your `:source-paths` or in some third-party `.jar` library you are using.
////
some-library/components/foo` のような絶対的な要求は、ローカルファイルシステムからファイルをロードしようとする `node` とは異なり、コンパイラがクラスパス上で `some-library/components/foo.js` を探すことを意味します。同じクラスパスのルールが適用されるので、ファイルは `:source-paths` にあるか、使用しているサードパーティの `.jar` ライブラリにあるかもしれません。

////
Relative requires are resolved by first looking at the current namespace and then resolving a relative path from that name. In the above example we are in `demo/app.cljs` to the `./bar` require resolves to `demo/bar.js`, so it is identical to `(:require ["/demo/bar"])`.
////
相対的なrequireは、まず現在の名前空間を見て、その名前からの相対パスを解決します。上の例では、 `demo/app.cljs` から `./bar` の require は `demo/bar.js` に解決されるので、 `(:require ["/demo/bar"])` と同じになります。

////
IMPORTANT: The files must not be physically located in the same directory. The lookup for the file appears on the classpath instead. This is unlike node which expects relative requires to always resolve to physical files.
////
重要：ファイルは物理的に同じディレクトリにあってはいけません。ファイルの検索は、代わりにクラスパス上で行われます。これは、相対的な要求が常に物理的なファイルに解決されることを期待するnodeとは異なります。

////
.Example File Structure with Separate Paths
////
.例 パスが分かれているファイル構造

```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── demo
            └── app.cljs
    └── js
        └── demo
            └── bar.js
```

=== 言語サポート
//Language Support

////
IMPORTANT: It is expected that the classpath only contains JavaScript that can be consumed without any pre-processing by the Compiler. `npm` has a very similar convention.
////
重要: クラスパスには、コンパイラが前処理をしなくても消費できるJavaScriptだけが含まれていることが期待されています。npm` にもよく似た規約があります。

////
The Closure Compiler is used for processing all JavaScript found on the classpath using its `ECMASCRIPT_NEXT` language setting. What exactly this setting means is not well documented but it mostly represents the next generation JavaScript code which might not even be supported by most browsers yet. ES6 is very well supported as well as most ES8 features. Similarly to standard CLJS this will be compiled down to ES5 with polyfills when required.
////
Closure Compilerは、クラスパス上で見つかった全てのJavaScriptを、その言語設定である `ECMASCRIPT_NEXT` を使って処理します。この設定が正確に何を意味するのかはよくわかっていませんが、ほとんどのブラウザではまだサポートされていないかもしれない次世代のJavaScriptコードを表しています。ES6は非常によくサポートされており、ほとんどのES8の機能もサポートされています。標準的なCLJSと同様に、これは必要に応じてポリフィルを用いてES5にコンパイルされます。

////
Since the Closure Compiler is getting constant updates newer features will be available over time. Just don't expect to use the latest cutting edge preview features to be available immediately. Somewhat recent additions like `async/await` already work quite well.
////
Closure Compilerは常にアップデートされていますので、新しい機能は徐々に利用可能になっていきます。ただ、最新の最先端のプレビュー機能がすぐに使えるとは思わないでください。最近追加された `async/await` のような機能は、すでに十分に機能しています。

////
The JS should be written using ES Module Syntax using `import` and `export`. JS files can include other JS files and reference CLJS code directly. They may also access `npm` packages directly with one caveat.
////
JSは、 `import` と `export` を使って、ESモジュール構文を使って書く必要があります。JSファイルは、他のJSファイルをインクルードしたり、CLJSのコードを直接参照することができます。また、 `npm` パッケージに直接アクセスすることもできますが、ひとつ注意点があります。

```js
// regular JS require
import Foo, { something } from "./other.js";

// npm require
import React from "react";

// require CLJS or Closure Library JS
import cljs from "goog:cljs.core";

export function inc(num) {
  return cljs.inc(1);
}
```

////
IMPORTANT: Due to strict checking of the Closure Compiler it is not possible to use the `import * as X from "npm";` syntax when requiring CLJS or npm code. It is fine to use when requiring other JS files.
////
重要：Closure Compilerの厳密なチェックにより、CLJSやnpmのコードを必要とする場合、 `import * as X from "npm";` の構文を使用することはできません。他のJSファイルを必要とする場合には問題なく使用できます。

=== JavaScriptの方言
//JavaScript Dialects

////
Since there are many popular JavaScript dialects (JSX, CoffeeScript, etc) that are not directly parsable by the Closure Compiler we need to pre-process them before putting them onto the classpath. https://babeljs.io/[babel] is commonly used in the JavaScript world so we are going to use `babel` to process `.jsx` files as an example here.
////
一般的なJavaScriptの方言（JSX、CoffeeScriptなど）には、Closure Compilerでは直接解析できないものが多いため、クラスパスに置く前に前処理を行う必要があります。https://babeljs.io/[babel]はJavaScriptの世界でよく使われているので、ここでは例として `.jsx` ファイルを処理するために `babel` を使用します。

////
.Example shadow-cljs.edn Config
////
.例 shadow-cljs.edn の設定

```
{:source-paths
 ["src/main"
  "src/gen"]
 ...}
```

////
.Example File Structure
////
.例 ファイル構成

```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── demo
            └── app.cljs
    └── js
        ├── .babelrc
        └── demo
            └── bar.jsx
```

////
IMPORTANT: Notice how `src/js` is not added to `:source-paths` which means it will not be on the classpath.
////
重要： `src/js` が `:source-paths` に追加されていないことに注目してください。これはクラスパスに含まれないことを意味します。

.src/js/demo/bar.jsx
```jsx
import React from "react";

function myComponent() {
  return <h1>JSX!</h1>;
}

export { myComponent };
```

////
We run https://babeljs.io/docs/usage/cli/[babel] to convert the files and write them to the configured `src/gen` directory. Which directory you use it up to you. I prefer `src/gen` for generated files.
////
https://babeljs.io/docs/usage/cli/[babel]を実行してファイルを変換し、設定された `src/gen` ディレクトリに書き込んでいます。どのディレクトリを使うかはあなた次第です。私は生成されたファイルには `src/gen` を使いたい。

```bash
$ babel src/js --out-dir src/gen
# or during development
$ babel src/js --out-dir src/gen --watch
```

////
`babel` itself is configured via the `src/js/.babelrc`. See the official https://babeljs.io/docs/plugins/transform-react-jsx/[example for JSX].
////
`babel` 自体は `src/js/.babelrc` を通して設定されます。公式 https://babeljs.io/docs/plugins/transform-react-jsx/[example for JSX] を参照してください。

////
.JSX minimal .babelrc
////

```json
{
  "plugins": ["transform-react-jsx"]
}
```

////
Once `babel` writes the `src/gen/demo/bar.js` it will be available to use via ClojureScript and will even be hot loaded just like your ClojureScript sources.
////
いったん `babel` が `src/gen/demo/bar.js` を書けば、それは ClojureScript を通して使用できるようになり、ClojureScript のソースと同じようにホットロードされることもあります。

////
IMPORTANT: `shadow-cljs` currently does not provide any support for running those transformation steps. Please use the standard tools (eg. `babel`, `coffeescript`, etc.) directly until it does.
////

=== JSからCLJSへのアクセス
//Access CLJS from JS

////
The JS sources can access all your ClojureScript (and the Closure Library) directly by importing their namespaces with a `goog:` prefix which the Compiler will rewrite to expose the namespace as the default ES6 export.
////
JSソースは、名前空間を `goog:` というプレフィックスでインポートすることで、すべてのClojureScript（およびClosure Library）に直接アクセスすることができます。このプレフィックスは、コンパイラが名前空間をデフォルトのES6エクスポートとして公開するように書き換えます。


```
import cljs, { keyword } from "goog:cljs.core";

// construct {:foo "hello world"} in JS
cljs.array_map(keyword("foo"), "hello world");
```


////
TIP: The `goog:` prefix currently only works for ES6 file. `require("goog:cljs.core")` does not work.
////
ヒント：現在、 `goog:` という接頭辞は、ES6ファイルにしか使えません。`require("goog:cljs.core")` は動作しません。

== cljsjs.* の移行について [[cljsjs]]
//Migrating cljsjs.* [[cljsjs]]

////
> CLJSJS is an effort to package Javascript libraries to be able to use them from within ClojureScript.
////
> CLJSJSは、Javascriptのライブラリをパッケージ化して、ClojureScriptから利用できるようにしようという試みです。

////
Since `shadow-cljs` can access <<npm, npm packages>> directly we do not need to rely on re-packaged https://github.com/cljsjs/packages[CLJSJS] packages.
////
`shadow-cljs` は <<npm, npm packages>> に直接アクセスできるので、再パッケージ化された https://github.com/cljsjs/packages[CLJSJS] packages に頼る必要はありません。

////
However many CLJS libraries are still using CLJSJS packages and they would break with `shadow-cljs` since it doesn't support those anymore. It is however very easy to mimick those `cljsjs` namespaces since they are mostly build from `npm` packages anyways. It just requires one shim file that maps the `cljsjs.thing` back to its original `npm` package and exposes the expected global variable.
////
しかし、多くの CLJS ライブラリはまだ CLJSJS パッケージを使用しており、 `shadow-cljs` はそれらをもうサポートしていないので、それらは壊れてしまいます。しかし、これらの `cljsjs` 名前空間を模倣するのはとても簡単です。なぜなら、それらはほとんど `npm` パッケージから構築されているからです。それには、 `cljsjs.thing` を元の `npm` パッケージにマップして、期待されるグローバル変数を公開する shim ファイルが必要です。

////
For React this requires a file like `src/cljsjs/react.cljs`:
////
Reactの場合は、 `src/cljsjs/react.cljs` のようなファイルが必要です。

```
(ns cljsjs.react
  (:require ["react" :as react]
            ["create-react-class" :as crc]))
```

```
(js/goog.object.set react "createClass" crc)
(js/goog.exportSymbol "React" react)
```

////
Since this would be tedious for everyone to do manually I created the https://github.com/thheller/shadow-cljsjs[`shadow-cljsjs`]
library which provides just that. It does not include every package but I’ll keep adding them and contributions are very welcome as well.
////
これは誰もが手動で行うのは面倒なので、私は https://github.com/thheller/shadow-cljsjs[`shadow-cljsjs`] というライブラリを作りました。
ライブラリを作成しました。すべてのパッケージが含まれているわけではありませんが、これからも追加していきますので、ご協力をお願いします。

////
NOTE: The `shadow-cljsjs` library only provides the shim files. You’ll still need to
`npm install` the actual packages yourself.
////
注：`shadow-cljsjs` ライブラリは、shimファイルを提供するだけです。実際のパッケージは、自分で
自分で実際のパッケージを `npm install` する必要があります。


=== CLJSJSを使ってみませんか?
//Why not use CLJSJS?

////
CLJSJS packages basically just take the package from `npm` and put them into a `.jar` and re-publish them via https://clojars.org[clojars]. As a bonus they often bundle Externs. The compiler otherwise does nothing with these files and only prepends them to the generated output.
////
CLJSJSのパッケージは、基本的に `npm` からパッケージを取り出し、 `.jar` に入れて、https://clojars.org[clojars]で再公開するだけです。おまけにExternsもバンドルされています。コンパイラはこれらのファイルに対して何もせず、生成された出力の先頭に追加するだけです。

////
This was very useful when we had no access to `npm` directly but has certain issues since not all packages are easily combined with others. A package might rely on `react` but instead of expressing this via `npm` https://github.com/cljsjs/packages/tree/master/material-ui[they] bundle their own `react`. If you are not careful you could end up including 2 different `react` versions in your build which may lead to very confusing errors or at the very least increase the build size substantially.
////
これは、 `npm` に直接アクセスできないときには非常に便利でしたが、すべてのパッケージが他のパッケージと簡単に結合できるわけではないので、ある種の問題があります。あるパッケージは `react` に依存しているかもしれませんが、 `npm` を通してこれを表現するのではなく、 https://github.com/cljsjs/packages/tree/master/material-ui[彼らは] 自分自身の `react` をバンドルします。注意しないと、2つの異なる `react` バージョンをビルドに含めることになり、非常に紛らわしいエラーが発生したり、少なくともビルドサイズが大幅に大きくなったりする可能性があります。

////
Apart from that not every `npm` package is available via CLJSJS and keeping the package versions in sync requires manual work, which means packages are often out of date.
////
また、すべての `npm` パッケージがCLJSJSで利用できるわけではなく、パッケージのバージョンを同期させるには手作業が必要なため、パッケージが古くなってしまうこともあります。

////
`shadow-cljs` does not support CLJSJS at all to avoid conflicts in your code. One library might attempt to use the "old" `cljsjs.react` while another uses the newer `(:require ["react"])` directly. This would again lead to 2 versions of `react` on your page again.
////
`shadow-cljs` は、コード内の競合を避けるために、CLJSJS を全くサポートしません。あるライブラリが古い`cljsjs.react` を使おうとする一方で、別のライブラリはより新しい `(:require ["react"])` を直接使うかもしれません。そうすると、再びページ上に2つのバージョンの `react` が存在することになります。

////
So the only thing we are missing are the bundled Externs. In many instances these are not required due to improved <<infer-externs, externs inference>>. Often those Externs are generated using third-party tools which means they are not totally accurate anyways.
////
そのため、唯一欠けているのはバンドルされているExternsです。多くの場合、<<infer-externs, externs inference>>が改善されたため、これらは必要ありません。また、これらのExternsはサードパーティのツールを使って生成されていることが多いので、いずれにしても完全には正確ではありません。

////
Conclusion: Use <<npm, npm>> directly. Use <<infer-externs, :infer-externs auto>>.
////
結論: <<npm, npm>> を直接使う。<<infer-externs, :infer-externs auto>>を使う。
