= REPL

////
The REPL is a very powerful tool to have when working with Clojure(Script) code. `shadow-cljs` provides several built-in variants that let you get started quickly as well as variants that are integrated into your standard builds.
////
REPLは、Clojure(Script)のコードを扱う際に、非常に強力なツールです。shadow-cljs` は、すぐに始められるいくつかのビルトインバージョンと、標準的なビルドに統合されるバージョンを提供します。

////
When you quickly want to test out some code the built-in REPLs should be enough. If you need more complex setups that also do stuff on their own it is best to use an actual build.
////
いくつかのコードをすぐにテストしたい場合は、内蔵のREPLで十分です。自分で何かをするような、より複雑なセットアップが必要な場合は、実際のビルドを使うのが一番です。

== ClojureScript REPL

////
By default you can choose between a `node-repl` and a `browser-repl`. They both work similarly and the differentiating factor is that one runs in a managed `node.js` process while the others opens a Browser Window that will be used to eval the actual code.
////
デフォルトでは、 `node-repl` と `browser-repl` のどちらかを選択することができます。どちらも似たような動作をしますが、違いは、一方がマネージドな `node.js` プロセスで動作するのに対し、他方は実際のコードを評価するために使用されるブラウザウィンドウを開くことです。

=== Node REPL [[node-repl]]

```bash
$ shadow-cljs node-repl
```
////
This starts a blank CLJS REPL with an already connected `node` process.
////
これは、すでに接続されている `node` プロセスで、空の CLJS REPL を開始します。

////
IMPORTANT: If you exit the Node REPL the `node` process is also killed!
////
重要：Node REPLを終了すると、 `node` プロセスもキルされます。

////
`node-repl` lets you get started without any additional configuration. It has access to all your code via the usual means, ie. `(require '[your.core :as x])`. Since it is not connected to any build it does not do any automatic rebuilding of code when your files change and does not provide hot-reload.
////
node-repl` を使えば、追加の設定をすることなく、すぐに使い始めることができます。node-replは、 `(require '[your.core :as x])` という通常の方法で、あなたのすべてのコードにアクセスします。ビルドに接続されていないので、ファイルが変更されてもコードの自動再構築は行われず、ホットリロードも提供されません。

=== Browser REPL [[browser-repl]]

```bash
$ shadow-cljs browser-repl
```

////
This starts a blank CLJS REPL and will open an associated Browser window where the code will execute. Besides running in the Browser this has all the same functionality as the above `node-repl`.
////
これは、空のCLJS REPLを起動し、コードが実行される関連するブラウザのウィンドウを開きます。ブラウザ上で実行されるだけでなく、上記の `node-repl` と同じ機能を持っています。

////
IMPORTANT: If you close the Browser window the REPL will stop working.
////
重要：ブラウザウィンドウを閉じると、REPLは動作しなくなります。

=== ビルドに特化した REPL [[build-repl]]

////
`node-repl` and `browser-repl` work without any specific build configuration. That means they'll only do whatever you tell them to do but nothing on their own.
////
`node-repl` と `browser-repl` は、特定のビルド構成なしに動作します。つまり、あなたが指示したことだけを実行し、自分では何もしないということです。

////
If you want to build a specific thing you should configure a build using one of the provided build-targets. Most of them automatically inject the necessary code for a ClojureScript REPL. It should not require any additional configuration. For the build CLJS REPL to work you need 2 things
////
特定のものをビルドしたい場合は、提供されているビルドターゲットの1つを使ってビルドを設定する必要があります。それらのほとんどは、ClojureScript REPLに必要なコードを自動的に注入します。それは追加の設定を必要としないはずです。ビルドCLJS REPLが動作するためには、次の2つが必要です。

////
. a running `watch` for your build
. connect the JS runtime of the `:target`. Meaning if you are using the `:browser` target you need to open a Browser that has the generated JS loaded. For node.js builds that means running the `node` process.
////
ビルドのための実行中の `watch` です。
ターゲットのJSランタイムを接続します。つまり、 `:browser` ターゲットを使用している場合、生成されたJSがロードされているブラウザを開く必要があります。node.jsのビルドの場合は、 `node` プロセスの実行を意味します。

////
Once you have both you can connect to the CLJS REPL via the command line or from the Clojure REPL.
////
両方を入手したら、コマンドラインまたはClojure REPLからCLJS REPLに接続できます。

///
.CLI
```bash
$ shadow-cljs watch build-id
...

# different terminal
$ shadow-cljs cljs-repl build-id
shadow-cljs - connected to server
[3:1]~cljs.user=>
```
///

.CLI
```bash
$ shadow-cljs watch build-id
...

# 異なるターミナル
$ shadow-cljs cljs-repl build-id
shadow-cljs - connected to server
[3:1]~cljs.user=>
```

.REPL
```bash
$ shadow-cljs clj-repl
...
[2:0]~shadow.user=> (shadow/watch :browser)
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (341 files, 1 compiled, 0 warnings, 3,19s)
:watching
[2:0]~shadow.user=> (shadow/repl :browser)
[2:1]~cljs.user=>
```

////
TIP: Type `:repl/quit` to exit the REPL. This will only exit the REPL, the `watch` will remain running.
////
TIP: REPLを終了するには、 `:repl/quit` と入力してください。これは REPL を終了するだけで、 `watch` は引き続き実行されます。

////
TIP: You may run multiple `watch` "workers" in parallel and connect/disconnect to their REPLs at any given time.
////
ヒント: 複数の `watch` 「ワーカー」を並行して実行し、任意の時間にそれらの REPL に接続/切断することができます。

////
.No connected runtime error.
////
.No connected のランタイムエラーが発生しました。

``` text
[3:1]~cljs.user=> (js/alert "foo")
There is no connected JS runtime.
```

////
If you see this you need to open your App in the Browser or start the `node` process.
////
これが表示された場合、ブラウザでアプリを開くか、 `node` プロセスを開始する必要があります。

== Clojure REPL

////
A Clojure REPL is also provided in addition to the provided ClojureScript REPLs. This is can be used to control the `shadow-cljs` process and run all other build commands through it. You can start with a Clojure REPL and then upgrade it to a CLJS REPL at any point (and switch back).
////
提供されているClojureScript REPLに加えて、Clojure REPLも提供されています。これは、 `shadow-cljs` プロセスを制御し、他のすべてのビルドコマンドを実行するために使用できます。Clojure REPLから始めて、いつでもCLJS REPLにアップグレードすることができます(そして元に戻すこともできます)。

////
.Running from the CLI
////
.CLIからの実行

```bash
$ shadow-cljs clj-repl
...
shadow-cljs - REPL - see (help), :repl/quit to exit
[1:0]~shadow.user=>
```

////
The `shadow.cljs.devtools.api` namespace has functions that map more or less 1:1 to the CLI counterparts. It is aliased as `shadow` by default.
////
名前空間 `shadow.cljs.devtools.api` には、CLI に対応する関数とほぼ1対1に対応する関数があります。デフォルトでは `shadow` という名前でエイリアスされています。

////
.Example commands
////


////
```clojure
;; shadow-cljs watch foo
(shadow.cljs.devtools.api/watch :foo)
;; this is identical, due to the provided ns alias
(shadow/watch :foo)
;; shadow-cljs watch foo --verbose
(shadow/watch :foo {:verbose true})
;; shadow-cljs compile foo
(shadow/compile :foo)
;; shadow-cljs release foo
(shadow/release :foo)

;; shadow-cljs browser-repl
(shadow/browser-repl)
;; shadow-cljs node-repl
(shadow/node-repl)
;; shadow-cljs cljs-repl foo
(shadow/repl :foo)

;; Once you are in a CLJS REPL you can use
:repl/quit
;; or
:cljs/quit
;; to drop back down to CLJ.
```
////

```clojure
;; shadow-cljs watch foo
(shadow.cljs.devtools.api/watch :foo)

;; これは、nsのエイリアスが用意されているため、同じです。
(shadow/watch :foo)

;; shadow-cljs watch foo --verbose
(shadow/watch :foo {:verbose true})

;; shadow-cljs compile foo
(shadow/compile :foo)

;; shadow-cljs release foo
(shadow/release :foo)

;; shadow-cljs browser-repl
(shadow/browser-repl)

;; shadow-cljs node-repl
(shadow/node-repl)

;; shadow-cljs cljs-repl foo
(shadow/repl :foo)

;; CLJS REPLに入ったら、:repl/quit や cljs/quit を使ってCLJに戻ることができます。

```

=== 組み込み [[embedded]]

////
It is also possible to use `shadow-cljs` entirely from within any other CLJ process. As long as the `thheller/shadow-cljs` artifact was loaded on the classpath you are good to go.
////
また、他の CLJ プロセスの中から完全に `shadow-cljs` を使用することも可能です。クラスパスに `thheller/shadow-cljs` がロードされていれば、問題ありません。

////
.Example using `lein repl`
////
.lein repl` を使った例

```bash
$ lein repl
nREPL server started on port 57098 on host 127.0.0.1 - nrepl://127.0.0.1:57098
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
...

user=> (require '[shadow.cljs.devtools.server :as server])
nil
user=> (server/start!)
...
:shadow.cljs.devtools.server/started
user=> (require '[shadow.cljs.devtools.api :as shadow])
nil
user=> (shadow/compile :foo)
...
```

////
You can stop the embedded server by running `(shadow.cljs.devtools.server/stop!)`. This will also stop all running build processes.
////
(shadow.cljs.devtools.server/stop!)` を実行することで、組み込みサーバを停止することができます。これにより、実行中のすべてのビルドプロセスも停止します。

////
IMPORTANT: If you want to switch to a CLJS REPL this may require additional setup in the tool you used to start the server in. Since `lein` will default to using nREPL it will require configuring additional nREPL `:middleware`. When using `clj` you are good to go since it doesn't use nREPL.
////
重要: CLJS REPLに切り替えたい場合は、サーバの起動に使用したツールで追加の設定が必要になる場合があります。lein` はデフォルトで nREPL を使用するので、追加の nREPL `:middleware` を設定する必要があります。clj` を使用する場合は、nREPLを使用しないので、問題ありません。

