////
The `:target :react-native` produces code that is meant to integrate into the default `react-native` tooling (eg. `metro`). Tools like `expo` which wrap those tools should automatically work and require no additional setup.
////
`:target :react-native` は、デフォルトの `react-native` ツール (例: `metro` ) に統合することを意図したコードを生成します。これらのツールをラップした `expo` のようなツールは自動的に動作し、追加の設定は必要ありません。

////
You will need the same basic <<config,main configuration>> as in other targets (like
`:source-paths`), the build specific config is very minimal and requires at least 2 options (besides `:target` itself)
////
他のターゲット（`:source-paths` など）と同じ基本的な <<config,main configuration>> が必要です。
`:source-paths`), ビルド固有の設定は非常に少なく、少なくとも2つのオプションが必要です (`:target` 自体の他に)。


////
[horizontal]
`:init-fn`:: (required). The namespace-qualified symbol of your apps init function. This function will be called once on startup and should probably render something.
`:output-dir`:: (required). The directory used to write output files.
////
[horizontal]
`:init-fn`:: (必須) アプリのinit関数の名前空間修飾されたシンボルです。この関数は起動時に一度だけ呼び出され、おそらく何かをレンダリングするはずです。
`:output-dir`:: (必須) (必須). 出力ファイルを書き込むためのディレクトリです。

// TODO: Thomas mentioned that node can be picky and sometimes output-dir is useful...an example would be nice.

////
.Sample :react-native config
////
.サンプル :react-native の設定

```
{:source-paths [...]
 :dependencies [...]
 ...
 :builds
 {:app
  {:target :react-native
   :init-fn demo.app/init
   :output-dir "app"}}}
```

////
When compiled this results in a `app/index.js` file intended to be used as an entry point for the `react-native` tools. During development the `:output-dir` will contain many more files but you should only reference the generated `app/index.js` directly. A `release` build will only generated the optimized `app/index.js` and requires no additional files.
////
これをコンパイルすると、 `react-native` ツールのエントリーポイントとして使用される `app/index.js` ファイルが生成されます。開発中、 `:output-dir` にはさらに多くのファイルが格納されますが、生成された `app/index.js` を直接参照するだけにしてください。リリース ` のビルドでは、最適化された `app/index.js` が生成されるだけで、追加のファイルは必要ありません。

== React Native

////
There are two ways to use `react-native`, "plain" `react-native`, which allows you to use native code and libraries and the one "wrapped" in https://expo.io/[expo] (described below). All the steps described above are sufficient to start using shadow-cljs with the plain `react-native`. See this example repo:
////
`react-native` には、ネイティブコードやライブラリを使用できるプレーンな `react-native` と https://expo.io/[expo] （後述）でラップされた `react-native` の2つの使用方法があります。上記で説明したすべての手順は、プレーンな `react-native` で shadow-cljs を使い始めるのに十分なものです。このサンプルレポをご覧ください。

- https://github.com/thheller/reagent-react-native

== Expo

////
https://expo.io/[expo] makes working with `react-native` quite easy. There are two provided example setups.
////
https://expo.io/[expo] を使うと、 `react-native` の作業がとても簡単になります。2つのサンプルセットアップが用意されています。

- https://github.com/thheller/fulcro-expo
- https://github.com/thheller/reagent-expo

////
Both examples where generated using `expo init ...` and the only adjusted change in the config was adding the proper `entryPoint` to the generated `app.json`.
////
どちらの例も `expo init ...` を使用して生成されており、設定で調整した唯一の変更点は、生成された `app.json` に適切な `entryPoint` を追加したことです。


```
{
  "expo": {
    "name": "hello-world",
    "slug": "reagent-expo",
    ...
    "entryPoint":"./app/index.js",
    ...
  }
}
```

////
`expo` requires that a React Component is registered on startup which can be done manually or by using the `shadow.expo/render-root` function which takes care of creating the Component and instead directly expects a React Element instance to start rendering.
////
`expo` では、起動時に React Component が登録される必要があります。これは手動で行うこともできますし、Component の作成を行い、代わりに React Element インスタンスがレンダリングを開始することを直接期待する `shadow.expo/render-root` 関数を使用することもできます。

////
.From the Reagent https://github.com/thheller/reagent-expo/blob/2c73ed0513a8f5050b250c0c7e53b9ae7543cee9/src/main/test/app.cljs#L34-L40[example]
////

.Reagent から https://github.com/thheller/reagent-expo/blob/2c73ed0513a8f5050b250c0c7e53b9ae7543cee9/src/main/test/app.cljs#L34-L40[example]

```
(defn start
  {:dev/after-load true}
  []
  (expo/render-root (r/as-element [root])))

(defn init []
  (start))
```

////
`init` is called once on startup. Since the example doesn't need to do any special setup it just calls `start` directly. `start` will be called repeatedly when `watch` is running each time after the code changes were reloaded. The `reagent.core/as-element` function can be used to generate the required React Element from the reagent hiccup markup.
////
`init` は起動時に一度だけ呼ばれます。この例では特別な設定をする必要がないので、単に `start` を直接呼び出します。 `start` は、コードの変更がリロードされた後に `watch` が実行されるたびに、繰り返し呼び出されます。 `reagent.core/as-element`関数は、reagent hiccupのマークアップから必要なReact Elementを生成するために使用することができます。
