////
When you want to run your CLJS tests against a browser on some kind of CI server you'll need to
be able to run the tests from a command line and get back a status code. Karma is a well-known
and supported test runner that can do this for you, and `shadow-cljs` includes a target that
can add the appropriate wrappers around your tests so they will work in it.
////
CLJSのテストをある種のCIサーバ上でブラウザに対して実行したい場合、次のことが必要になります。
コマンドラインからテストを実行して、ステータスコードを返すことができる必要があります。Karmaはよく知られており
そして、 `shadow-cljs` には、あなたのテストの周りに適切なラッパーを追加できるターゲットが含まれています。
ターゲットが含まれており、テストに適切なラッパーを追加することで、テストがKarmaで動作するようになります。

=== Karmaのインストール
//Installing Karma

////
See their http://karma-runner.github.io[website] for full instructions. You'll typically need
something like this is your `package.json`:
////
詳しい説明は、 http://karma-runner.github.io[website] をご覧ください。通常、次のようなものが必要になります。 `package.json` には以下のようなものが必要です。


```json
{
  "name": "CITests",
  "version": "1.0.0",
  "description": "Testing",
  ...
  "devDependencies": {
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cljs-test": "^0.1.0",
    ...
  },
  "author": "",
  "license": "MIT"
}
```
////
So, you need Karma, a browser launcher, and the cljs-test integration.
////
つまり、Karma、ブラウザランチャー、そしてcljs-testの統合が必要なのです。

=== Build
// The Build

////
The build options are:
////
ビルドのオプションは次のとおりです。

////
[horizontal]
`:target`::     `:karma`
`:output-to`::  A path/filename for the js file.
`:ns-regexp`::  (optional) A regex to match the test namespaces, defaults to "-test$
////

[horizontal]
`:target`:: `:karma`(カルマ)
`:output-to`:: `:karma`:  jsファイルのパス/ファイル名です。
`:ns-regexp`::  (オプション) テストの名前空間にマッチさせる正規表現、デフォルトは "-test$" です。

////
So you might have something like this:
////
つまり、次のようになります。

```
{...
 :builds
 {:ci
  {:target :karma
   :output-to  "target/ci.js"
   :ns-regexp  "-spec$"}}}
```

////
You also need a `karma.conf.js`:
////
また、 `karma.conf.js` も必要です。

```javascript
module.exports = function (config) {
    config.set({
        browsers: ['ChromeHeadless'],
        // The directory where the output file lives
        basePath: 'target',
        // The file itself
        files: ['ci.js'],
        frameworks: ['cljs-test'],
        plugins: ['karma-cljs-test', 'karma-chrome-launcher'],
        colors: true,
        logLevel: config.LOG_INFO,
        client: {
            args: ["shadow.test.karma.init"],
            singleRun: true
        }
    })
};
```

////
then you can run the tests as follows (assuming you've installed global executables of the tools):
////
とすると、以下のようにテストを実行することができます（ツールのグローバル実行ファイルがインストールされていることが前提です）。

```bash
$ shadow-cljs compile ci
$ karma start --single-run
12 01 2018 01:19:24.222:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
12 01 2018 01:19:24.224:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
12 01 2018 01:19:24.231:INFO [launcher]: Starting browser ChromeHeadless
12 01 2018 01:19:24.478:INFO [HeadlessChrome 0.0.0 (Mac OS X 10.12.6)]: Connected on socket TcfrjxVKmx7xN6enAAAA with id 85554456
LOG: 'Testing boo.sample-spec'
HeadlessChrome 0.0.0 (Mac OS X 10.12.6): Executed 1 of 1 SUCCESS (0.007 secs / 0.002 secs)
```

