////
There is an additional target that is intended to integrate CLJS into an existing JS project. The output can seamlessly integrate with existing JS tools (eg. webpack, browserify, babel,
create-react-app, ...) with little configuration.
////
既存の JS プロジェクトにCLJSを統合することを目的とした追加ターゲットがあります。この出力は、既存の JS ツール（例：webpack、browserify 、babel.com）とシームレスに統合することができます。
create-react-appなど）とシームレスに統合できます。

////
[horizontal]
`:output-dir`:: The path for the output files are written to, defaults to `node_modules/shadow-cljs`.
`:entries`:: (required) A vector of namespace symbols that should be compiled
////
[horizontal]
`:output-dir`:: デフォルトでは `node_modules/shadow-cljs` となります。
`:entries`:: (必須) コンパイルされるべき名前空間シンボルのベクトル。

////
.Example `shadow-cljs.edn` config
////
.Example `shadow-cljs.edn` の設定
```
{...
 :builds
 {:code
  {:target :npm-module
   :entries [demo.foo]}}}
```

////
If you use the default `:output-dir` of `"node_modules/shadow-cljs"` you can access the declared namespaces by using `require("shadow-cljs/demo.foo")` in JS. When using something not in `node_modules` you must include them using a relative path. With `:output-dir "out"` that would be `require("./out/demo.foo")` from your project root.
////
デフォルトの `:output-dir` である `"node_modules/shadow-cljs"` を使用すると、JS で `require("shadow-cljs/demo.foo")` を使用して、宣言された名前空間にアクセスすることができます。node_modules` にないものを使用する場合は、相対パスを使ってインクルードする必要があります。:output-dir "out"` では、プロジェクトルートからの `require("./out/demo.foo")` となります。


////
If you plan to distribute code on NPM, then you may want to use the <<NodeLibrary, `:node-library` target>> instead since it allows for a finer level of control over exports and optimization.
////
NPMでコードを配布する予定であれば、代わりに<<NodeLibrary, `:node-library` target>>を使用した方が、エクスポートや最適化をより細かく制御できるので良いでしょう。

== 最適化の作業
//Working with Optimizations

////
Unlike the `:node-library` target, the module target does not know what you want to call the symbols you're exporting, so it just exports them as-is. If you use advanced compilation, then everything will get a minified munged name!
////
gnome-library` ターゲットとは異なり、module ターゲットはエクスポートするシンボルをどのように呼びたいかわからないので、そのままエクスポートします。高度なコンパイルを使用している場合は、すべてのシンボルにminified mungedの名前が付けられます。

////
This is easy to remedy, simply add `:export` metadata on any symbols that you want to preserve:
////
保存したいシンボルに `:export` メタデータを追加するだけで、簡単に解決できます。

```
(ns demo.foo)

(def ^:export foo 5.662)

(defn ^:export bar [] ...)
```

////
This is a standard annotation that is understood by ClojureScript and prevents Google Closure from
renaming an artifact. JS code will still be able to access them after optimizations. Without the `^:export` hint the closure-compiler will likely have removed or renamed them.
////
これは、ClojureScript で理解される標準的なアノテーションで、Google Closureがアーティファクトの名前を変更するのを防ぎます。
がアーティファクトの名前を変更するのを防ぎます。 JS コードは最適化後もそれらにアクセスすることができます。^:export` のヒントがなければ、クロージャコンパイラがそれらを削除したり、名前を変更したりするでしょう。

```
var ns = require("shadow-cljs/demo.foo");

ns.foo;
ns.bar();
```

